<?php

/**
 * @file
 * Contains iccwc_scrollup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iccwc_scrollup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.iccwc_scrollup':
      $output = '';
      $output .= '<h3>' . t('ICCWC Scrollup') . '</h3>';
      $output .= '<p>' . t('Scroll Up to the page. Provide advanced configuration for administrator to manage behaviour of scrolling.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function iccwc_scrollup_install() {
  $defaultThemeName = \Drupal::config('system.theme')->get('default');
  \Drupal::configFactory()->getEditable('iccwc_scrollup.settings')
    ->set('iccwc_scrollup_position', 1)
    ->set('iccwc_scrollup_button_bg_color', '#CCCCCC')
    ->set('iccwc_scrollup_button_hover_bg_color', '#000000')
    ->set('iccwc_scrollup_title', 'Scroll up')
    ->set('iccwc_scrollup_window_position', '600')
    ->set('iccwc_scrollup_speed', '0')
    ->set('iccwc_scrollup_themename', [$defaultThemeName])
    ->save();
}

/**
 * Implements hook_preprocess_page().
 */
function iccwc_scrollup_preprocess_page(&$variables) {

  $config = \Drupal::config('iccwc_scrollup.settings');
  $theme_selected = $config->get('iccwc_scrollup_themename');
  $active_theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  if (array_keys($theme_selected, $active_theme)) {
    $variables['#attached']['library'][] = 'iccwc_scrollup/iccwc_scrollup';
    $variables['#attached']['drupalSettings']['iccwc_scrollup_position'] = $config->get('iccwc_scrollup_position');
    $variables['#attached']['drupalSettings']['iccwc_scrollup_button_bg_color'] = $config->get('iccwc_scrollup_button_bg_color');
    $variables['#attached']['drupalSettings']['iccwc_scrollup_button_hover_bg_color'] = $config->get('iccwc_scrollup_button_hover_bg_color');
    $variables['#attached']['drupalSettings']['iccwc_scrollup_title'] = $config->get('iccwc_scrollup_title');
    $variables['#attached']['drupalSettings']['iccwc_scrollup_hoover_title'] = $config->get('iccwc_scrollup_hoover_title');
    $variables['#attached']['drupalSettings']['iccwc_scrollup_window_position'] = $config->get('iccwc_scrollup_window_position');
    $variables['#attached']['drupalSettings']['iccwc_scrollup_speed'] = $config->get('iccwc_scrollup_speed');
    $variables['#attached']['drupalSettings']['iccwc_scrollup_themename'] = $config->get('iccwc_scrollup_themename');
  }

}
