<?php

/**
 * @file
 * Contains edw_scrollup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function edw_scrollup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.edw_scrollup':
      $output = '';
      $output .= '<h3>' . t('EDW Scrollup') . '</h3>';
      $output .= '<p>' . t('Scroll Up to the page. Provide advanced configuration for administrator to manage behaviour of scrolling.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function edw_scrollup_preprocess_page(&$variables) {
  $config = \Drupal::config('edw_scrollup.settings');
  $theme_selected = $config->get('edw_scrollup_themename');
  $active_theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();

  if (array_keys($theme_selected, $active_theme)) {
    $variables['#attached']['library'][] = 'edw_scrollup/edw_scrollup';
    $variables['#attached']['drupalSettings']['edw_scrollup_position'] = $config->get('edw_scrollup_position');
    $variables['#attached']['drupalSettings']['edw_scrollup_button_bg_color'] = $config->get('edw_scrollup_button_bg_color');
    $variables['#attached']['drupalSettings']['edw_scrollup_button_hover_bg_color'] = $config->get('edw_scrollup_button_hover_bg_color');
    $variables['#attached']['drupalSettings']['edw_scrollup_title'] = $config->get('edw_scrollup_title');
    $variables['#attached']['drupalSettings']['edw_scrollup_hover_title'] = $config->get('edw_scrollup_hover_title');
    $variables['#attached']['drupalSettings']['edw_scrollup_window_position'] = $config->get('edw_scrollup_window_position');
    $variables['#attached']['drupalSettings']['edw_scrollup_speed'] = $config->get('edw_scrollup_speed');
    $variables['#attached']['drupalSettings']['edw_scrollup_themename'] = $config->get('edw_scrollup_themename');
  }
}
